[package]
name = "rocksy"
version = "0.1.0"
authors = ["Caspar Krieger <git@asparck.com>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.0"
tokio-core = "0.1.13"
lazy_static = "1.0.0"
unicase = "2.0.0"
clap = "2"
regex = "0.2"
